#
# Problem 28 - Number spiral diagnosis
#
# Find the sum of the numbers on a 1001 x 1001 grid generated by a
# clockwise spiral of consecutive numbers starting at 1.
#


def main():
    # Excluding the central number 1, our spiral generates 4 sequences,
    # 4n^2 - 2n + 1
    # 4n^2 + 1
    # 4n^2 + 2n + 1
    # 4n^2 + 4n + 1
    # So the sum of the four courners of each square in the spiral is
    # P(n) = 16n^2 + 4n + 4
    # where n = 1 is the 3 x 3 square, n = 2 is the 5 x 5 square etc.
    # So the sum of the n x n square, n odd, is P(2n - 1)
    # So the total is 1 + Sum(n = 1, n = 500)(P(n)).

    total = 1
    for n in range(1, 501):
        total += (16 * n * n) + (4 * n) + 4

    print(total)


if __name__ == "__main__":
    main()
