#
# Problem 28 - Number spiral diagnosis
#
# Find the sum of the numbers on a 1001 x 1001 grid generated by a
# clockwise spiral of consecutive numbers starting at 1.
#


def main():
    # Excluding the central number 1, our spiral generates 4 sequences,
    # 4n^2 - 2n + 1
    # 4n^2 + 1
    # 4n^2 + 2n + 1
    # 4n^2 + 4n + 1
    # So the sum of the four courners of each square in the spiral is
    # P(n) = 16n^2 + 4n + 4
    # where n = 1 is the 3 x 3 square, n = 2 is the 5 x 5 square etc.
    # So the sum of the n x n square, n odd, is P(2n - 1)
    # So the total is 1 + Sum(n = 1, n = 500)(P(n)).
    # We can calculate the total by using well-known formulae, giving,
    # total = 1 + 26n/3 + 10n^2 + 16n^3/3

    print(1 + (26 * 500) / 3 + 10 * 500 * 500 + (16 * 500 * 500 * 500) / 3)


if __name__ == "__main__":
    main()
